-- MySQL Script generated by MySQL Workbench
-- Пн 11 июн 2018 03:49:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `ks-installer`.`hosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`hosts` ;

-- -----------------------------------------------------
-- Table `ks-installer`.`ports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`ports` ;

-- -----------------------------------------------------
-- Table `ks-installer`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`requests` ;

-- -----------------------------------------------------
-- Table `ks-installer`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`errors` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
