-- MySQL Script generated by MySQL Workbench
-- Пн 11 июн 2018 03:49:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ks-installer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ks-installer` DEFAULT CHARACTER SET utf8 ;
USE `ks-installer` ;

-- -----------------------------------------------------
-- Table `ks-installer`.`hosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`hosts` ;

CREATE TABLE IF NOT EXISTS `ks-installer`.`hosts` (
  `id` VARCHAR(36) NOT NULL,
  `hostname` VARCHAR(45) NOT NULL,
  `ipmi_address` VARCHAR(15) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hostname_UNIQUE` (`hostname` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ks-installer`.`ports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`ports` ;

CREATE TABLE IF NOT EXISTS `ks-installer`.`ports` (
  `name` VARCHAR(16) NOT NULL,
  `jun` SMALLINT(2) NOT NULL,
  `vlan` SMALLINT(2) NOT NULL,
  `mac` VARCHAR(17) NULL DEFAULT NULL,
  `host` VARCHAR(36) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_ports_host_idx` (`host` ASC),
  UNIQUE INDEX `mac_UNIQUE` (`mac` ASC),
  CONSTRAINT `fk_ports_host`
    FOREIGN KEY (`host`)
    REFERENCES `ks-installer`.`hosts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ks-installer`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`requests` ;

CREATE TABLE IF NOT EXISTS `ks-installer`.`requests` (
  `id` VARCHAR(36) NOT NULL,
  `srcip` VARCHAR(16) NOT NULL,
  `method` VARCHAR(4) NOT NULL,
  `size` INT NOT NULL,
  `url` VARCHAR(32) NOT NULL,
  `status` SMALLINT(2) NOT NULL,
  `user_agent` VARCHAR(128) NOT NULL,
  `requested_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ks-installer`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ks-installer`.`errors` ;

CREATE TABLE IF NOT EXISTS `ks-installer`.`errors` (
  `id` VARCHAR(36) NOT NULL,
  `request_id` VARCHAR(36) NOT NULL,
  `internal_code` TINYINT(1) UNSIGNED NOT NULL,
  `http_status` SMALLINT(2) UNSIGNED NOT NULL,
  `source` VARCHAR(18) NULL,
  `link` VARCHAR(32) NOT NULL,
  `displayed_title` VARCHAR(64) NOT NULL,
  `displayed_detail` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC),
  CONSTRAINT `fk_request_id`
    FOREIGN KEY (`request_id`)
    REFERENCES `ks-installer`.`requests` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
