-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `ks-installer`.`requests` 
CHANGE COLUMN `size` `size` INT(11) NOT NULL ,
CHANGE COLUMN `status` `status` SMALLINT(2) NOT NULL ;

ALTER TABLE `ks-installer`.`jobs` 
CHANGE COLUMN `action` `action` TINYINT(1) NOT NULL ,
CHANGE COLUMN `state` `state` TINYINT(1) NOT NULL DEFAULT 0 ,
CHANGE COLUMN `is_failed` `is_failed` TINYINT(1) NOT NULL DEFAULT 0 ;

CREATE TABLE IF NOT EXISTS `ks-installer`.`ports` (
  `name` VARCHAR(16) NOT NULL,
  `jun` SMALLINT(2) NOT NULL,
  `vlan` SMALLINT(2) NOT NULL,
  `boundle` VARCHAR(6) NULL DEFAULT NULL,
  `mac` VARCHAR(17) NULL DEFAULT NULL,
  `host` VARCHAR(36) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_ports_host_idx` (`host` ASC),
  UNIQUE INDEX `mac_UNIQUE` (`mac` ASC),
  CONSTRAINT `fk_ports_host`
    FOREIGN KEY (`host`)
    REFERENCES `ks-installer`.`hosts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `ks-installer`.`macs` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
